### ISSUE TITLE
React.js Portfolio

### ISSUE THREAD

**Issue by mctripp10** [mctripp10/mctripp10.github.io#1]
Using this tutorial to get started: https://www.youtube.com/watch?v=k-Pi5ZMxHWY&list=WL&index=7&t=14s

**Comment by mctripp10** [comment]
(10/17/2023) Looked around at some HTML templates and tutorials to get started

**Comment by mctripp10** [comment]
(10/18/2023) (10:28) Initialized workspace/project files and got started on YouTube tutorial

**Comment by mctripp10** [comment]
(10/19/2023) (23:08) Started creating navbar and some basic body content

**Comment by mctripp10** [comment]
(10/20/2023) (41:10) Finished main page content, added card system with 3 cards, and started portfolio section

**Comment by mctripp10** [comment]
(10/23/2023) (56:16) Completed developedbyed's React portfolio website tutorial! Now moving on to personalizing it as my own website.

**Comment by techwizard31** [comment]
what is the issue man ?

**Comment by mctripp10** [comment]
@techwizard31 This was more of a progress tracker than an actual issue haha. I wanted to make a react portfolio to practice react.js. It is still in progress so that is why this is not yet closed.

**Comment by mctripp10** [comment]
The website is complete enough to go live with it on GitHub pages. I will be updating it and adding projects over time, but it is complete enough to close this issue.
